In [1]:
import numpy as np
print("numpy imported successfully ")

numpy imported successfully 


Creating Numpy array


In [2]:
arr = np.array([1,2,3,4,5,6])
print("Array :",arr)
print("Type :",type(arr))

Array : [1 2 3 4 5 6]
Type : <class 'numpy.ndarray'>


In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("This is 2D array :\n")
print(arr2)

This is 2D array :

[[1 2 3]
 [4 5 6]]


Array attributes


In [5]:
print('Shape :',arr2.shape)

Shape : (2, 3)


In [6]:
print('Size :',arr2.size)

Size : 6


In [7]:
print('Data Type :',arr2.dtype)

Data Type : int64


Arrays of Zeros


In [9]:
zeros = np.zeros((2,3))
print("Zeros :\n",zeros)

Zeros :
 [[0. 0. 0.]
 [0. 0. 0.]]


Array of Once


In [13]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [83]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5])

# 2D array
arr2 = np.array([[1,2,3],[4,5,6]])

# Full (all same number)
full = np.full((2,2), 7)
print("Full:\n", full)

# Identity matrix
eye = np.eye(3)
print("Identity:\n", eye)

# Linearly spaced
arr_lin = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
print("Linspace:", arr_lin)


Full:
 [[7 7]
 [7 7]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Linspace: [0.   0.25 0.5  0.75 1.  ]


Array with a range


In [15]:
range_arr = np.arange(0,10,2) #start ,stop ,step
print(range_arr)

[0 2 4 6 8]


Random Number


In [94]:
# Random floats 0 to 1
rand = np.random.rand(2,3)
print("Random float array:\n", rand)

# Random integers
rand_int = np.random.randint(0, 10, (2,3))  # 0-9
print("Random integer array:\n", rand_int)

print("the three Arrays Are :")
print("\n")
arr = np.random.randint(0, 10,( 3, 2, 2)) 
 # shape = (num_matrices, rows, cols)
print(arr)


Random float array:
 [[0.32870626 0.1991003  0.7971593 ]
 [0.42278791 0.96251482 0.09967989]]
Random integer array:
 [[4 1 5]
 [4 1 5]]
the three Arrays Are :


[[[8 9]
  [1 7]]

 [[3 8]
  [2 8]]

 [[5 3]
  [2 6]]]


Basic Array Operation


In [29]:
a= np.array([1,2,3,4])
b= np.array([4,5,6,7])

print("addition :",a+b)
print("substraction :",a-b)
print("Element Wise Multiplicaiton :",a*b)
print("Element Wise Division :\n",a/b)
print("Exponent :",a**2)

addition : [ 5  7  9 11]
substraction : [-3 -3 -3 -3]
Element Wise Multiplicaiton : [ 4 10 18 28]
Element Wise Division :
 [0.25       0.4        0.5        0.57142857]
Exponent : [ 1  4  9 16]


Indexing and Slicing


In [31]:
arr = np.array([10,20,30,40,50])
print("Original Array :",arr)

Original Array : [10 20 30 40 50]


In [ ]:
#Accessing element using Slicing
print("first Element :",arr[0])
print("last Element :",arr[-1])

first Element : 10
last Element : 50


In [ ]:
#Slicing

print("Element from Index 1 t0 3 :",arr[1:4])
print("Every other element :", arr[::2])   # start, end, step

Element from Index 1 t0 3 : [20 30 40]
Every other element : [10 30 50]


2D array Indexing


In [35]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2d array :\n",arr2d)

2d array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
print("Element at row 1st index and col 2 index :",arr2d[1,2])
print("First row :" , arr2d[0])
print("First column :",arr2d[:,0])
print("SubArray :\n",arr2d[0:2 ,1:3])

Element at row 1st index and col 2 index : 6
First row : [1 2 3]
First column : [1 4 7]
SubArray :
 [[2 3]
 [5 6]]


Reshaping And Flattering Array


In [ ]:
arr = np.arange(1,13)
print("OG array :",arr)

#reshape to 3x4 Matrix
arr_reshaped = arr.reshape(3,4)
print("reshaped array in 3X4 :\n",arr_reshaped)



#flattern back to 1d
arr_1d = arr_reshaped.flatten()
print("converted 1d array from 2d array using flatten:\n",arr_1d)

OG array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped array in 3X4 :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix 1: [1 2 3 4]
Matrix 2: [5 6 7 8]
Matrix 3: [ 9 10 11 12]
converted 1d array from 2d array using flatten:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


Universal Functions (ufuncs)

ufuncs are element-wise fast functions.


In [69]:
arr = np.array([1,2,3,4,5])

print("Sum :",np.sum(arr))
print("Mean :",np.mean(arr))
print("Max :",np.max(arr))
print("Min :",np.min(arr))
print("Standart Deviation :", np.std(arr))
print("Square Root :",np.sqrt(arr))
print("Sin values :", np.sin(arr))

Sum : 15
Mean : 3.0
Max : 5
Min : 1
Standart Deviation : 1.4142135623730951
Square Root : [1.         1.41421356 1.73205081 2.         2.23606798]
Sin values : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


Boolean Indexing (Filtering Arrays)

Boolean indexing lets you select elements based on a condition.


In [70]:
import numpy as np

In [74]:
arr = np.array([10,20,30,40,50,60])

#Getting element greater than 25
arr_element = arr[arr > 25]
print("Greater than 25 : ",arr_element)

# Combination of Condition 

arr_combination = arr[(arr >20) & (arr < 60)]
print("Array greater than 20 and less than 60 :",arr_combination)


Greater than 25 :  [30 40 50 60]
Array greater than 20 and less than 60 : [30 40 50]


Stacking and Splitting Arrays

Stacking Arrays
Combine arrays vertically or horizontally.


In [79]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#horizontal Stack 

H_stack = np.hstack((a,b))
print("your horizontal stack is :",H_stack)

# Vertical Stack

V_stack = np.vstack((a,b))
print("your Vertical stack is :",V_stack)


your horizontal stack is : [1 2 3 4 5 6]
your Vertical stack is : [[1 2 3]
 [4 5 6]]


Splitting Arrays

Split arrays into multiple parts.


In [90]:
arr = np.array([1,2,3,4,5,6])

#spliting into 3 parts
split_arr = np.split(arr,3)
print(split_arr)

print("OR")

m1, m2, m3 = np.split(arr, 3)
print("Matrix 1:", m1)
print("Matrix 2:", m2)
print("Matrix 3:", m3)

[array([1, 2]), array([3, 4]), array([5, 6])]
OR
Matrix 1: [1 2]
Matrix 2: [3 4]
Matrix 3: [5 6]


Matrix Operations

NumPy can do linear algebra and matrix math easily.


In [81]:
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])

#Addition
print("A + B:\n", A + B)

# Matrix multiplication (dot product)
print("A dot B:\n", np.dot(A,B))

# Element-wise multiplication
print("Element-wise A*B:\n", A * B)

# Transpose
print("Transpose of A:\n", A.T)
print("Transpose of B:\n",B.T)

A + B:
 [[ 6  8]
 [10 12]]
A dot B:
 [[19 22]
 [43 50]]
Element-wise A*B:
 [[ 5 12]
 [21 32]]
Transpose of A:
 [[1 3]
 [2 4]]
Transpose of B:
 [[5 7]
 [6 8]]


Aggregation and Axis Operations

Axis lets you do operations along rows or columns.


In [82]:
arr2d = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
])

print("Sum of all Element :",np.sum(arr2d))
print("Sum along Cols :",np.sum(arr2d,axis=0))
print("Sum along Rows :",np.sum(arr2d, axis=1))

Sum of all Element : 45
Sum along Cols : [12 15 18]
Sum along Rows : [ 6 15 24]


Fancy Indexing

Fancy indexing lets you select arbitrary elements using arrays of indices.


In [96]:
arr = np.array([10,20,30,40,50])
indices = [0,2,4]

print(arr[indices])

[10 30 50]


In [99]:
arr2D = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
])

rows = [1,2]   # both are rows
cols = [2,2]    # both are cols

print(arr2D[rows,cols])


[6 9]


Question:

Create 5 random 3x3 matrices

Add a vector Array [1,2,3] to each matrix (broadcasting)

Apply square root (np.sqrt) to all elements

Find the sum of each matrix


In [2]:
import numpy as np

In [8]:
Matrix = np.random.randint(0,10,(5,3,3))   #start , end ,(NoOfMatrix,Rows,Cols)
print("Original Matrix : ",Matrix)

Original Matrix :  [[[3 7 7]
  [8 4 0]
  [7 2 4]]

 [[3 6 1]
  [8 6 0]
  [1 4 8]]

 [[2 8 1]
  [2 0 5]
  [8 5 3]]

 [[1 1 5]
  [0 0 2]
  [4 9 7]]

 [[1 1 4]
  [6 4 7]
  [2 6 8]]]


In [22]:
vector = np.array([1,2,3])

Matrix_added = Matrix + vector

print("After Adding Vector :\n",Matrix_added)
#squring of matrix 

Squared_Matix = np.sqrt(Matrix_added)
display(Squared_Matix)


After Adding Vector :
 [[[ 4  9 10]
  [ 9  6  3]
  [ 8  4  7]]

 [[ 4  8  4]
  [ 9  8  3]
  [ 2  6 11]]

 [[ 3 10  4]
  [ 3  2  8]
  [ 9  7  6]]

 [[ 2  3  8]
  [ 1  2  5]
  [ 5 11 10]]

 [[ 2  3  7]
  [ 7  6 10]
  [ 3  8 11]]]


array([[[2.        , 3.        , 3.16227766],
        [3.        , 2.44948974, 1.73205081],
        [2.82842712, 2.        , 2.64575131]],

       [[2.        , 2.82842712, 2.        ],
        [3.        , 2.82842712, 1.73205081],
        [1.41421356, 2.44948974, 3.31662479]],

       [[1.73205081, 3.16227766, 2.        ],
        [1.73205081, 1.41421356, 2.82842712],
        [3.        , 2.64575131, 2.44948974]],

       [[1.41421356, 1.73205081, 2.82842712],
        [1.        , 1.41421356, 2.23606798],
        [2.23606798, 3.31662479, 3.16227766]],

       [[1.41421356, 1.73205081, 2.64575131],
        [2.64575131, 2.44948974, 3.16227766],
        [1.73205081, 2.82842712, 3.31662479]]])

In [32]:
Final_matrix = np.sum(Squared_Matix, axis=(1,2))
print(Final_matrix)

[22.81799665 21.56923315 20.96426102 19.33994346 21.92663712]


QUESTION 2
Create a (100, 5) NumPy array with random integers between 0 and 100.

Rows = students

Columns = subjects

Find the average marks of each student → shape (100,).

Find the average marks of each subject → shape (5,).

Find the top 5 students (by total marks) → return their indices and total scores.


In [34]:

import numpy as np

#step 1 by creating random integer b/w 0 - 100

marks = np.random.randint(0 ,100 ,(100,5))
print(marks)

[[59 85  9 17 67]
 [28 76 17 41 54]
 [23 66 52 48 59]
 [13 13 73  8 99]
 [88 64 47 67 69]
 [45 16 85 37 31]
 [79 89 43 23 16]
 [13 52 67 71  2]
 [28 85 36 79 48]
 [17  2 68 33 24]
 [48 54  5  8 52]
 [77 61 43  6 34]
 [ 9 68 74  0  3]
 [98 60  5 23 52]
 [12 48 82 18 32]
 [95 99 91 54 97]
 [51 38 71 66 60]
 [77 70 53 20 54]
 [77 43  9 66 40]
 [24 57  4 77 95]
 [62 80  3 89  2]
 [25 79 79 94 15]
 [13 23 54 11 31]
 [11 71 96 56 95]
 [97 22 13 38  0]
 [39 56 32 30 12]
 [97 40 63 58 73]
 [30 69 68 87 45]
 [45 67 46 70 86]
 [ 0 60 89 56 96]
 [43  4  6 90 80]
 [55 69 26 19 21]
 [74 18 74 92 27]
 [38 60 72 81 21]
 [55 59 73 17 81]
 [57 51 78 77  2]
 [60 71 95 56 50]
 [24 56 62 45 98]
 [80 67 97 74 44]
 [90 31 98 90 60]
 [60 30 25 71 11]
 [37  2 30 48 27]
 [33 58 55 35 58]
 [ 4  1 63 49 85]
 [61  6  7 57 70]
 [51 99 77 72 69]
 [96 94 70  1 56]
 [63 17 21 21 62]
 [ 9 40 53  2 16]
 [16 35 63 75 57]
 [53 55 35 33  8]
 [93 83 30 45 23]
 [43 23 24 53 56]
 [23 10 15 43 87]
 [47 47 80 33 79]
 [44 43 59

In [ ]:
#  print(marks.shape)    will return the shape of the matrix (100 ,5)

#Step 2 average Marks of Student

student_avg = np.mean(marks,axis=1)
print(student_avg)



[47.4 43.2 49.6 41.2 67.  42.8 50.  41.  55.2 28.8 33.4 44.2 30.8 47.6
 38.4 87.2 57.2 54.8 47.  51.4 47.2 58.4 26.4 65.8 34.  33.8 66.2 59.8
 62.8 60.2 44.6 38.  57.  54.4 57.  53.  66.4 57.  72.4 73.8 39.4 28.8
 47.8 40.4 40.2 73.6 63.4 36.8 24.  49.2 36.8 54.8 39.8 35.6 57.2 62.
 42.  54.8 50.8 64.2 46.6 56.4 48.8 65.4 61.4 38.4 69.6 21.  72.6 25.8
 12.8 48.4 32.4 43.8 45.2 80.2 55.8 47.6 46.4 62.6 60.6 58.6 24.  55.2
 35.6 45.4 69.  43.6 52.8 65.2 40.8 68.4 46.4 39.8 38.2 28.6 41.8 51.6
 44.6 56.6]


First five student avg : [47.4 43.2 49.6 41.2 67. ]


In [ ]:
#step 3 Finding the Average marks of each subject

Average_Each_Sub_marks = np.mean(marks,axis = 0)
print(Average_Each_Sub_marks)

[46.66 50.14 54.16 48.62 47.22]


In [44]:
#finding total Marks of each student
total_marks = np.sum(marks , axis = 1)
print(total_marks)

[237 216 248 206 335 214 250 205 276 144 167 221 154 238 192 436 286 274
 235 257 236 292 132 329 170 169 331 299 314 301 223 190 285 272 285 265
 332 285 362 369 197 144 239 202 201 368 317 184 120 246 184 274 199 178
 286 310 210 274 254 321 233 282 244 327 307 192 348 105 363 129  64 242
 162 219 226 401 279 238 232 313 303 293 120 276 178 227 345 218 264 326
 204 342 232 199 191 143 209 258 223 283]


In [48]:
sorted_marks = np.argsort(total_marks)
print(sorted_marks)

[70 67 48 82 69 22 95 41  9 12 72 10 25 24 53 84 50 47 31 94 14 65 40 93
 52 44 43 90  7  3 96 56  5  1 87 73 11 98 30 74 85 78 92 60 18 20  0 77
 13 42 71 62 49  2  6 58 19 97 88 35 33 17 51 57  8 83 76 61 99 32 37 34
 54 16 21 81 27 29 80 64 55 79 28 46 59 89 63 23 26 36  4 91 86 66 38 68
 45 39 75 15]


In [52]:
# taking max marks five student from last
top_student = sorted_marks[-5:]

print("Top student Index ",top_student)
print("Top Student Marks :\n",marks[top_student])

Top student Index  [68 45 39 75 15]
Top Student Marks :
 [[87 42 99 84 51]
 [51 99 77 72 69]
 [90 31 98 90 60]
 [43 79 95 95 89]
 [95 99 91 54 97]]


NumPy Broadcasting

Definition:
Broadcasting is NumPy’s way of automatically expanding arrays of different shapes so they can be used together in operations without writing loops.


In [53]:
arr = np.array([1, 2, 3, 4])

print(arr + 5)  # Add 5 to every element
print(arr * 10)  # Multiply 10 to every element

[6 7 8 9]
[10 20 30 40]


In [55]:
#Row Vector with Matrix

A = np.array([[1, 2, 3],[4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)


[[11 22 33]
 [14 25 36]]


In [56]:
#Column Vector with Matrix

A = np.array([[1, 2, 3],
              [4, 5, 6]])

c = np.array([[10],
              [20]])

print(A + c)

[[11 12 13]
 [24 25 26]]


Shape Rules (important ⚠️)

Two arrays can be broadcast together if their shapes are compatible:

Compare shapes from right to left.

Dimensions must be equal OR one of them must be 1.

(2, 3) with (3,) ✅

(4, 1, 3) with (3,) ✅

(2,3) with (2,) ❌ (mismatch)


Real Example

Imagine you have student's marks in 3 subjects:


In [ ]:
marks =np.array([
            [50, 60, 70],    # marks of student 1   subject  wise
            [80, 90,100],    # marks of student 2
            [40, 50, 60]     # marks of student 3
])

Weights = np.array([0.2,0.3,0.5])   # wight of each subjects

weighted = marks*Weights

print(weighted)


[[10. 18. 35.]
 [16. 27. 50.]
 [ 8. 15. 30.]]


That’s broadcasting! It replaces big loops with 1 line.
